// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: produce-events.proto

package com.cseiu.passnet.saga.recruitmentsaga;

public final class ProduceEvents {
  private ProduceEvents() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CreateClassEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:produceEvents.CreateClassEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string teacherId = 1;</code>
     */
    java.lang.String getTeacherId();
    /**
     * <code>string teacherId = 1;</code>
     */
    com.google.protobuf.ByteString
        getTeacherIdBytes();

    /**
     * <code>repeated string taIds = 2;</code>
     */
    java.util.List<java.lang.String>
        getTaIdsList();
    /**
     * <code>repeated string taIds = 2;</code>
     */
    int getTaIdsCount();
    /**
     * <code>repeated string taIds = 2;</code>
     */
    java.lang.String getTaIds(int index);
    /**
     * <code>repeated string taIds = 2;</code>
     */
    com.google.protobuf.ByteString
        getTaIdsBytes(int index);
  }
  /**
   * Protobuf type {@code produceEvents.CreateClassEvent}
   */
  public  static final class CreateClassEvent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:produceEvents.CreateClassEvent)
      CreateClassEventOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CreateClassEvent.newBuilder() to construct.
    private CreateClassEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CreateClassEvent() {
      teacherId_ = "";
      taIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CreateClassEvent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              teacherId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                taIds_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000002;
              }
              taIds_.add(s);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          taIds_ = taIds_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.internal_static_produceEvents_CreateClassEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.internal_static_produceEvents_CreateClassEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.CreateClassEvent.class, com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.CreateClassEvent.Builder.class);
    }

    private int bitField0_;
    public static final int TEACHERID_FIELD_NUMBER = 1;
    private volatile java.lang.Object teacherId_;
    /**
     * <code>string teacherId = 1;</code>
     */
    public java.lang.String getTeacherId() {
      java.lang.Object ref = teacherId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        teacherId_ = s;
        return s;
      }
    }
    /**
     * <code>string teacherId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTeacherIdBytes() {
      java.lang.Object ref = teacherId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        teacherId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TAIDS_FIELD_NUMBER = 2;
    private com.google.protobuf.LazyStringList taIds_;
    /**
     * <code>repeated string taIds = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getTaIdsList() {
      return taIds_;
    }
    /**
     * <code>repeated string taIds = 2;</code>
     */
    public int getTaIdsCount() {
      return taIds_.size();
    }
    /**
     * <code>repeated string taIds = 2;</code>
     */
    public java.lang.String getTaIds(int index) {
      return taIds_.get(index);
    }
    /**
     * <code>repeated string taIds = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTaIdsBytes(int index) {
      return taIds_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTeacherIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, teacherId_);
      }
      for (int i = 0; i < taIds_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, taIds_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTeacherIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, teacherId_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < taIds_.size(); i++) {
          dataSize += computeStringSizeNoTag(taIds_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getTaIdsList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.CreateClassEvent)) {
        return super.equals(obj);
      }
      com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.CreateClassEvent other = (com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.CreateClassEvent) obj;

      if (!getTeacherId()
          .equals(other.getTeacherId())) return false;
      if (!getTaIdsList()
          .equals(other.getTaIdsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TEACHERID_FIELD_NUMBER;
      hash = (53 * hash) + getTeacherId().hashCode();
      if (getTaIdsCount() > 0) {
        hash = (37 * hash) + TAIDS_FIELD_NUMBER;
        hash = (53 * hash) + getTaIdsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.CreateClassEvent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.CreateClassEvent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.CreateClassEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.CreateClassEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.CreateClassEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.CreateClassEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.CreateClassEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.CreateClassEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.CreateClassEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.CreateClassEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.CreateClassEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.CreateClassEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.CreateClassEvent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code produceEvents.CreateClassEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:produceEvents.CreateClassEvent)
        com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.CreateClassEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.internal_static_produceEvents_CreateClassEvent_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.internal_static_produceEvents_CreateClassEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.CreateClassEvent.class, com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.CreateClassEvent.Builder.class);
      }

      // Construct using com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.CreateClassEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        teacherId_ = "";

        taIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.internal_static_produceEvents_CreateClassEvent_descriptor;
      }

      @java.lang.Override
      public com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.CreateClassEvent getDefaultInstanceForType() {
        return com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.CreateClassEvent.getDefaultInstance();
      }

      @java.lang.Override
      public com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.CreateClassEvent build() {
        com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.CreateClassEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.CreateClassEvent buildPartial() {
        com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.CreateClassEvent result = new com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.CreateClassEvent(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.teacherId_ = teacherId_;
        if (((bitField0_ & 0x00000002) != 0)) {
          taIds_ = taIds_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.taIds_ = taIds_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.CreateClassEvent) {
          return mergeFrom((com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.CreateClassEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.CreateClassEvent other) {
        if (other == com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.CreateClassEvent.getDefaultInstance()) return this;
        if (!other.getTeacherId().isEmpty()) {
          teacherId_ = other.teacherId_;
          onChanged();
        }
        if (!other.taIds_.isEmpty()) {
          if (taIds_.isEmpty()) {
            taIds_ = other.taIds_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureTaIdsIsMutable();
            taIds_.addAll(other.taIds_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.CreateClassEvent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.CreateClassEvent) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object teacherId_ = "";
      /**
       * <code>string teacherId = 1;</code>
       */
      public java.lang.String getTeacherId() {
        java.lang.Object ref = teacherId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          teacherId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string teacherId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTeacherIdBytes() {
        java.lang.Object ref = teacherId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          teacherId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string teacherId = 1;</code>
       */
      public Builder setTeacherId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        teacherId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string teacherId = 1;</code>
       */
      public Builder clearTeacherId() {
        
        teacherId_ = getDefaultInstance().getTeacherId();
        onChanged();
        return this;
      }
      /**
       * <code>string teacherId = 1;</code>
       */
      public Builder setTeacherIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        teacherId_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList taIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureTaIdsIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          taIds_ = new com.google.protobuf.LazyStringArrayList(taIds_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated string taIds = 2;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getTaIdsList() {
        return taIds_.getUnmodifiableView();
      }
      /**
       * <code>repeated string taIds = 2;</code>
       */
      public int getTaIdsCount() {
        return taIds_.size();
      }
      /**
       * <code>repeated string taIds = 2;</code>
       */
      public java.lang.String getTaIds(int index) {
        return taIds_.get(index);
      }
      /**
       * <code>repeated string taIds = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTaIdsBytes(int index) {
        return taIds_.getByteString(index);
      }
      /**
       * <code>repeated string taIds = 2;</code>
       */
      public Builder setTaIds(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTaIdsIsMutable();
        taIds_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string taIds = 2;</code>
       */
      public Builder addTaIds(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTaIdsIsMutable();
        taIds_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string taIds = 2;</code>
       */
      public Builder addAllTaIds(
          java.lang.Iterable<java.lang.String> values) {
        ensureTaIdsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, taIds_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string taIds = 2;</code>
       */
      public Builder clearTaIds() {
        taIds_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string taIds = 2;</code>
       */
      public Builder addTaIdsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureTaIdsIsMutable();
        taIds_.add(value);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:produceEvents.CreateClassEvent)
    }

    // @@protoc_insertion_point(class_scope:produceEvents.CreateClassEvent)
    private static final com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.CreateClassEvent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.CreateClassEvent();
    }

    public static com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.CreateClassEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CreateClassEvent>
        PARSER = new com.google.protobuf.AbstractParser<CreateClassEvent>() {
      @java.lang.Override
      public CreateClassEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CreateClassEvent(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CreateClassEvent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CreateClassEvent> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.CreateClassEvent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SagaResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:produceEvents.SagaResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string message = 1;</code>
     */
    java.lang.String getMessage();
    /**
     * <code>string message = 1;</code>
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code produceEvents.SagaResponse}
   */
  public  static final class SagaResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:produceEvents.SagaResponse)
      SagaResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SagaResponse.newBuilder() to construct.
    private SagaResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SagaResponse() {
      message_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SagaResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.internal_static_produceEvents_SagaResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.internal_static_produceEvents_SagaResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.SagaResponse.class, com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.SagaResponse.Builder.class);
    }

    public static final int MESSAGE_FIELD_NUMBER = 1;
    private volatile java.lang.Object message_;
    /**
     * <code>string message = 1;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>string message = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, message_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, message_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.SagaResponse)) {
        return super.equals(obj);
      }
      com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.SagaResponse other = (com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.SagaResponse) obj;

      if (!getMessage()
          .equals(other.getMessage())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.SagaResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.SagaResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.SagaResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.SagaResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.SagaResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.SagaResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.SagaResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.SagaResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.SagaResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.SagaResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.SagaResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.SagaResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.SagaResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code produceEvents.SagaResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:produceEvents.SagaResponse)
        com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.SagaResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.internal_static_produceEvents_SagaResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.internal_static_produceEvents_SagaResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.SagaResponse.class, com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.SagaResponse.Builder.class);
      }

      // Construct using com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.SagaResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        message_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.internal_static_produceEvents_SagaResponse_descriptor;
      }

      @java.lang.Override
      public com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.SagaResponse getDefaultInstanceForType() {
        return com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.SagaResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.SagaResponse build() {
        com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.SagaResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.SagaResponse buildPartial() {
        com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.SagaResponse result = new com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.SagaResponse(this);
        result.message_ = message_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.SagaResponse) {
          return mergeFrom((com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.SagaResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.SagaResponse other) {
        if (other == com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.SagaResponse.getDefaultInstance()) return this;
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.SagaResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.SagaResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>string message = 1;</code>
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string message = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string message = 1;</code>
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string message = 1;</code>
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string message = 1;</code>
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:produceEvents.SagaResponse)
    }

    // @@protoc_insertion_point(class_scope:produceEvents.SagaResponse)
    private static final com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.SagaResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.SagaResponse();
    }

    public static com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.SagaResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SagaResponse>
        PARSER = new com.google.protobuf.AbstractParser<SagaResponse>() {
      @java.lang.Override
      public SagaResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SagaResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SagaResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SagaResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.cseiu.passnet.saga.recruitmentsaga.ProduceEvents.SagaResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_produceEvents_CreateClassEvent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_produceEvents_CreateClassEvent_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_produceEvents_SagaResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_produceEvents_SagaResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024produce-events.proto\022\rproduceEvents\"4\n" +
      "\020CreateClassEvent\022\021\n\tteacherId\030\001 \001(\t\022\r\n\005" +
      "taIds\030\002 \003(\t\"\037\n\014SagaResponse\022\017\n\007message\030\001" +
      " \001(\t2j\n\rEventProducer\022Y\n\027ProduceCreateCl" +
      "assEvent\022\037.produceEvents.CreateClassEven" +
      "t\032\033.produceEvents.SagaResponse\"\000B(\n&com." +
      "cseiu.passnet.saga.recruitmentsagab\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_produceEvents_CreateClassEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_produceEvents_CreateClassEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_produceEvents_CreateClassEvent_descriptor,
        new java.lang.String[] { "TeacherId", "TaIds", });
    internal_static_produceEvents_SagaResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_produceEvents_SagaResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_produceEvents_SagaResponse_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
