spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: false
        generate_statistics: false
        enable_lazy_load_no_trans: true
    show-sql: false
  h2:
    console:
      enabled: true
      path: /h2-console
  redis:
    host: viewcache
    port: 6379
springdoc:
  api-docs:
    path: /api-docs
  pathsToMatch: /**
  swagger-ui:
    path: /swagger-ui.html
grpc:
  port: 9090

saga:
  grpc:
    host: passnet-recruitment-saga
    port: 6565

view:
  posted-jobs:
    id: postedJobViews