spring:
  application:
    name: passnet-recruitment
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        format_sql: false
        generate_statistics: false
        enable_lazy_load_no_trans: true
    show-sql: false
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
springdoc:
  api-docs:
    path: /api-docs
  pathsToMatch: /**
  swagger-ui:
    path: /swagger-ui.html

view:
  posted-jobs:
    id: ${VIEW_CACHE_ID}
grpc:
  server:
    port: ${GRPC_PORT_LISTENER}
  client:
    saga-recruitment:
      address: 'static://${RECRUITMENT_SAGA_ADDRESS}'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
server:
  port: ${SERVER_PORT_LISTENER}