version: "3.7"

services:
  mypostgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=passnet-recruitment-app
      - POSTGRES_PASSWORD=tungduong98
      - POSTGRES_DB=passnet_recruitment
    ports:
      - "5432:5432"